### ISSUE TITLE
cp --update可否添加校验hash的功能

### ISSUE THREAD

**Issue by seahurt** [aliyun/ossutil#112]
使用 `ossutil64 cp -u -r /local/path oss://bucket/remote/path `上传，发现有一个文件本地和远程不一样，但是也给跳过了。

本地目录会在一段时间内一直新增文件，我用脚本每1分钟上传一次，在另外一台服务器每1分钟同步一次。

今天发现两边文件不一样。用rsync找出了出错的文件, 发现该文件只上传了30%左右，这个文件大小在1GB以上。

请问是否可以添加检验hash的功能，或者检查一下文件大小也好，不要只单纯的看一下时间戳

**Comment by huiguangjun** [comment]
ossutil 2.0 预览版(https://help.aliyun.com/zh/oss/developer-reference/command-line-tool-ossutil-version-2) 已发布，

该版本支持按照 对象大小校验。

如何从 ossutil 1.0 迁移到 ossutil 2.0，请参见 [迁移指南](https://help.aliyun.com/zh/oss/developer-reference/migration-guide/)
