### ISSUE TITLE
include参数无效

### ISSUE THREAD

**Issue by FlyStoneZz** [aliyun/ossutil#114]
![1](https://user-images.githubusercontent.com/45958641/79534855-58297c00-80ae-11ea-9510-8e2100eab8fd.png)
指定了include 并没有生效

**Comment by huiguangjun** [comment]
ossutil 2.0 预览版(https://help.aliyun.com/zh/oss/developer-reference/command-line-tool-ossutil-version-2) 已发布，

如何从 ossutil 1.0 迁移到 ossutil 2.0，请参见 [迁移指南](https://help.aliyun.com/zh/oss/developer-reference/migration-guide/)
