### ISSUE TITLE
FinishWithError but exit code 0

### ISSUE THREAD

**Issue by suconghou** [aliyun/ossutil#123]
use `ossutil  cp -r -f dist oss://path/to/dir/` to upload dir 

got 
```

FinishWithError: Total num: 16, size: 2,491,294. Error num: 3. OK num: 13(upload 10 files, 3 directories), Transfer size: 2,238,887.
73

```
with zero exit code.

In cI build it does not raise a failure which cause deployment error 

please update to no-zero exit code in this case.

**Comment by huiguangjun** [comment]
ossutil 2.0 预览版(https://help.aliyun.com/zh/oss/developer-reference/command-line-tool-ossutil-version-2) 已发布，

该版本规范了错误返回码。

如何从 ossutil 1.0 迁移到 ossutil 2.0，请参见 [迁移指南](https://help.aliyun.com/zh/oss/developer-reference/migration-guide/)
