### ISSUE TITLE
1.7.0版本，cp命令可以正常使用，ls命令返回错误

### ISSUE THREAD

**Issue by shatian114** [aliyun/ossutil#132]
1.7.0的版本
使用cp命令上传文件正常
使用 ‘ossutils ls oss://jcls/’ 命令返回:   Error: Get http://jcls.oss-cn-hongkong.aliyuncs.com/?delimiter=&encoding-type=url&marker=&max-keys=1000&prefix=: read tcp 192.168.137.254:48400->47.75.18.176:80: read: connection reset by peer, Bucket=jcls, Object=

**Comment by wangtaowei** [comment]
这个是网络问题导致的，可能是当时网络异常。
