### ISSUE TITLE
How to limit download speed

### ISSUE THREAD

**Issue by zen-xu** [aliyun/ossutil#138]

**Comment by Mad-Thanos** [comment]
the same question troubled me a few days.
`ossutil cp` command do not support options related to "max download speed", although there is a '--maxupspeed' to limit  uploading speed.

finally, I find a way:
step1. use `ossutil sign  --trafic-limit=1024000000` to generate a signed http url of your oss file
step2. use `wget http://.....` to download the file with speed limited

**Comment by wangtaowei** [comment]
thank your sugesstions ！
the version v1.7.6 will support it
