### ISSUE TITLE
增加hash比较更新

### ISSUE THREAD

**Issue by yuntaowu2000** [aliyun/ossutil#151]
希望sync和cp能增加hash的检查来进行文件更新，根据modified date会导致所有文件始终都需重新上传。

**Comment by alfoil** [comment]
+1

**Comment by xuxucode** [comment]
+1
某个场景: 
1. 首先从 OSS 下载到本地 local_dir，本地文件的 ModifiedTime 为当前时间（> OSS lastModified）
2. 再次从 local_dir 上传到 OSS，**导致所有文件重新上传**

**Comment by huiguangjun** [comment]
1. 已发布 [ossutil 2.0 预览版](https://help.aliyun.com/zh/oss/developer-reference/command-line-tool-ossutil-version-2/?spm=a2c4g.11186623.0.0.2aa347229ZbXdJ)

针对 目的过滤规则的命令 ，支持如下， 
--update：只对比修改时间，只同步源端新于目的端。
--size-only：只对比文件大小，只同步文件大小不一样的数据。
--checksum：对比crc64，优先对比文件大小，当文件大小一样时，再对比crc64。如果某一端crc64不存在，则判为不一致。考虑到本地crc64计算的问题，仅在对象间拷贝时有效。
