### ISSUE TITLE
跨账号使用 sync 的方法

### ISSUE THREAD

**Issue by leolcao** [aliyun/ossutil#157]
假设有2个阿里云账号，每个账号下，都是在一个区域创建了不同的 buckets，能用 sync 子命令跨账号 sync 数据吗。

参考了：https://help.aliyun.com/document_detail/256354.html?spm=a2c4g.11186623.0.0.32b4543evRxN3t

但是会出错。问题是如何设置2个账号下不同的 oss access key /secret 呢？上面实例上的 -i -k 设置的是哪个账号下的 oss accesskey/secret 呢？

```
./ossutil64 sync oss://examplebucket/srcfolder/  oss://testbucket/examplefolder/ -e oss-cn-shanghai.aliyuncs.com -i LTAI4Fw2NbDUCV8zYUzA****  -k 67DLVBkH7EamOjy2W5RVAHUY9H****
```

我这边得到的错误类似：

```
Error: oss: service returned error: StatusCode=403, ErrorCode=AccessDenied, ErrorMessage="The bucket you access does not belong to you.", RequestId=611CEC004453333530156597, Bucket=xxx, Object=
```

这里的 `Bucket=xxx` 是sync的第一个 source_oss 中的bucket，感觉是要求 source_oss 的bucket的访问权限是要开放的。

**Comment by wangtaowei** [comment]
目前不支持跨账号访问，用户配置的ak，sk必须对两个bucket都有读写权限。
