### ISSUE TITLE
希望sync命令能够增加参数使能够同步文件的修改时间

### ISSUE THREAD

**Issue by yashen** [aliyun/ossutil#182]
现在存在这样的问题，先从A同步到B,使用--update参数

ossutil sync  --update A B 

这个时候B中文件的修改时间是新建文件的时间，而不是源文件的修改时间,

这样再从B同步到A是，因为B上的文件较新就会全部同步

ossutil sync  --update B A

然后再A->B,又会发送同样的事情

**Comment by yashen** [comment]
不再需要了，我修改了下代码，上传下载文件后，使本地文件的时间戳同云端一致

**Comment by shiweijie** [comment]
> 不再需要了，我修改了下代码，上传下载文件后，使本地文件的时间戳同云端一致

请问怎么解决的
