### ISSUE TITLE
树莓派上下载文件panic 空指针

### ISSUE THREAD

**Issue by shellus** [aliyun/ossutil#19]
shellus@raspberrypi ~ $ ossutil cp "oss://wawa-disk/Website Backup/shuoxingba/db-2016-10-05.sql.tgz" ./
Total num: 1, size: 229,522,629. Dealed num: 0, OK size: 0, Progress: 0%

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11580]

goroutine 1 [running]:
sync/atomic.addUint64(0x49903c, 0x271668, 0x0, 0x76f6e708, 0x0)
        C:/Go/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/aliyun/ossutil/lib.(*CPMonitor).updateTransferSize(0x49901c, 0x271668, 0x0)
        C:/Users/shellus/go/src/github.com/aliyun/ossutil/lib/monitor.go:428 +0x34
github.com/aliyun/ossutil/lib.(*OssProgressListener).ProgressChanged(0x10868440, 0x1093dd40)
        C:/Users/shellus/go/src/github.com/aliyun/ossutil/lib/cp.go:88 +0x6c
github.com/aliyun/aliyun-oss-go-sdk/oss.publishProgress(0x470ca0, 0x10868440, 0x1093dd40)
        C:/Users/shellus/go/src/github.com/aliyun/aliyun-oss-go-sdk/oss/progress.go:43 +0x40
github.com/aliyun/aliyun-oss-go-sdk/oss.Bucket.downloadFileWithCp(0x1080a1b0, 0x10800760, 0x7e9018b1, 0x9, 0x7e9018bb, 0x2f, 0x10746ec0, 0x31, 0x271668, 0x0, ...)
        C:/Users/shellus/go/src/github.com/aliyun/aliyun-oss-go-sdk/oss/download.go:474 +0x608
github.com/aliyun/aliyun-oss-go-sdk/oss.Bucket.DownloadFile(0x1080a1b0, 0x10800760, 0x7e9018b1, 0x9, 0x7e9018bb, 0x2f, 0x10746ec0, 0x31, 0x271668, 0x0, ...)
        C:/Users/shellus/go/src/github.com/aliyun/aliyun-oss-go-sdk/oss/download.go:42 +0x1f8
github.com/aliyun/ossutil/lib.(*CopyCommand).ossResumeDownloadRetry(0x498f48, 0x10800780, 0x7e9018bb, 0x2f, 0x10746ec0, 0x31, 0xdae3cc5, 0x0, 0x271668, 0x0, ...)
        C:/Users/shellus/go/src/github.com/aliyun/ossutil/lib/cp.go:1831 +0xb8
github.com/aliyun/ossutil/lib.(*CopyCommand).downloadSingleFile(0x498f48, 0x10800780, 0x7e9018bb, 0x2f, 0xffffffff, 0xffffffff, 0xd0ff7ce3, 0xe, 0x195f6c23, 0x49aa38, ...)
        C:/Users/shellus/go/src/github.com/aliyun/ossutil/lib/cp.go:1776 +0x67c
github.com/aliyun/ossutil/lib.(*CopyCommand).downloadSingleFileWithReport(0x498f48, 0x10800780, 0x7e9018bb, 0x2f, 0xffffffff, 0xffffffff, 0xd0ff7ce3, 0xe, 0x195f6c23, 0x49aa38, ...)
        C:/Users/shellus/go/src/github.com/aliyun/ossutil/lib/cp.go:1717 +0x40
github.com/aliyun/ossutil/lib.(*CopyCommand).downloadFiles(0x498f48, 0x7e9018ab, 0x3f, 0x7e9018b1, 0x9, 0x7e9018bb, 0x2f, 0x7e9018eb, 0x2, 0xf, ...)
        C:/Users/shellus/go/src/github.com/aliyun/ossutil/lib/cp.go:1680 +0x1dc
github.com/aliyun/ossutil/lib.(*CopyCommand).RunCommand(0x498f48, 0x0, 0x0)
        C:/Users/shellus/go/src/github.com/aliyun/ossutil/lib/cp.go:1077 +0x6e4
github.com/aliyun/ossutil/lib.(*CommandManager).RunCommand(0x1072ff28, 0x7e9018a8, 0x2, 0x1070f8c8, 0x2, 0x3, 0x1070f8a0, 0xc4, 0x3204e7, 0xf7)
        C:/Users/shellus/go/src/github.com/aliyun/ossutil/lib/command_manager.go:89 +0xe0
github.com/aliyun/ossutil/lib.RunCommand(0x1070f8c0, 0x3, 0x4, 0x1070f8a0, 0x0, 0x0, 0x1)
        C:/Users/shellus/go/src/github.com/aliyun/ossutil/lib/command_manager.go:63 +0xbc
github.com/aliyun/ossutil/lib.ParseAndRunCommand(0x0, 0x1070f640)
        C:/Users/shellus/go/src/github.com/aliyun/ossutil/lib/command_manager.go:27 +0xec
main.main()
        C:/Users/shellus/go/src/github.com/aliyun/ossutil/ossutil.go:11 +0x14

文件是在windows7上使用go get 下载源码，然后使用GOOS=linux GOARCH=arm go build来编译到的。
然后在树莓派上运行。`ls` 之类的命令正常。但是`cp`时，空指针异常。

**Comment by baiyubin** [comment]
谢谢您的反馈，请使用阿里云官网编译出的版本， 请从  [https://help.aliyun.com/document_detail/50452.html](https://help.aliyun.com/document_detail/50452.html ) 上下载使用。

**Comment by shellus** [comment]
您好，您给出的页面没有linux arm架构release包。

**Comment by abo321** [comment]
谢谢您的问题。
已在官网发布最新版解决了这个问题。请从https://help.aliyun.com/document_detail/50452.html 上下载使用。

后续我们会在github release上提供build好的版本。
