### ISSUE TITLE
`sync`的选项 `--maxdownspeed` 不起作用

### ISSUE THREAD

**Issue by bakerwm** [aliyun/ossutil#230]
`ossutil` 版本 1.7.17
同步远程数据到本地，设定限速不起作用：
设置 `--maxdownspeed=10000`, 实际下载速度已超过 `30000 KB/s`, 最高到 `50000 KB/s`，限速功能未实现；截图如下

![fa38f91f231b9cd2f111ffe8a334113](https://github.com/aliyun/ossutil/assets/1317927/255fb7c8-62d0-42e3-bca3-6be0d78e3d72)

**Comment by huiguangjun** [comment]
ossutil 2.0 预览版(https://help.aliyun.com/zh/oss/developer-reference/command-line-tool-ossutil-version-2) 已发布，

该版本同时支持 上传 和 下载限速。

如何从 ossutil 1.0 迁移到 ossutil 2.0，请参见 [迁移指南](https://help.aliyun.com/zh/oss/developer-reference/migration-guide/)
