### ISSUE TITLE
版本错误

### ISSUE THREAD

**Issue by kybom** [aliyun/ossutil#33]
官网和go get下的版本都是1.0.0版本，为什么文档里面都说当前版本是：1.2.0

**Comment by abo321** [comment]
谢谢您的反馈。请从这里或者官网下载最新版本。

**Comment by kybom** [comment]
@abo321 从你给的地址下载的版本还是1.0.0
`root@local:~# ./ossutil64 -v
ossutil version: 1.0.0`
