### ISSUE TITLE
不能上传超过4GB的文件

### ISSUE THREAD

**Issue by bower820** [aliyun/ossutil#41]
通过 ossutil 1.4（Linux x86_64版，Ubuntu 17.10 64位） 版无法上传超过4GB的文件。同样的环境，使用 osscmd 刚正常。错误信息如下：

Total num: 1, size: 4,639,948,800. Dealed num: 0, OK size: 0, Progress: 0%
Total num: 1, size: 4,639,948,800. Dealed num: 0, Transfer size: 0. When error happens.
Error: Put http://XXXX.oss-cn-shenzhen.aliyuncs.com/V834394-01-7.3.iso?partNumber=3&uploadId=XXXXDB06B4D64B4B9DD9BA359FD8XXXX: EOF, File=/PATH/OracleLinux/V834394-01-7.3.iso!

**Comment by abo321** [comment]
上传的时候请指定--parallel或者--part-size参数降低并发数。单个文件大小100M，默认会分片上传，分片个数通过计算得到。4GB的文件，分片个数在12~15。如果您的终端CPU，mem，网络资源不够，会出现EOF的错误。
