### ISSUE TITLE
能否在Release页面提供编译好的版本？

### ISSUE THREAD

**Issue by abcfy2** [aliyun/ossutil#50]
我本地没有go编译环境，不知能否方便下使用者，直接在release之后上传各个对应的操作系统编译好的版本呢？

**Comment by brentybh** [comment]
这项目估计没人管了……自己编译吧，golang就一个文件夹的bin，设个gopath，很快的，编译完不要go环境直接删掉就行

**Comment by brentybh** [comment]
下载地址这里有
https://help.aliyun.com/document_detail/50452.html
