### ISSUE TITLE
Can we also have the binary release, it's much easier to have a binary release for download it in script, not installing it from scratch. 

### ISSUE THREAD

**Issue by georgedriver** [aliyun/ossutil#52]
Can we also have the binary release, it's much easier to have a binary release for download it in script, not installing it from scratch. 

Like `aliyun` cli does. https://github.com/aliyun/aliyun-cli/releases/download/v3.0.2/aliyun-cli-linux-amd64.tar.gz

Thanks.

**Comment by otarabai** [comment]
I found a download link for the latest binary release in this documentation page: https://www.alibabacloud.com/help/doc-detail/50452.htm

**Comment by wangtaowei** [comment]
https://www.alibabacloud.com/help/doc-detail/50452.htm 

The above url is the binary official website download address！
