### ISSUE TITLE
ossutil上传文件时，是否可以保留文件的修改时间

### ISSUE THREAD

**Issue by lesgle** [aliyun/ossutil#54]
举例如下：
a目录下有
a-2018-06-17.bak  (2018-06-17创建）
a-2018-06-18.bak  (2018-06-18创建）
a-2018-06-19.bak  (2018-06-19创建）

当我在2018-06-25号使用ossutil cp命令将这些文件上传到oss上时，文件的更新时间都变成上传时刻的时间2018-06-25，请问ossutil是否有选项，在上传或下载时可以保留原来文件的创建时间，以方便在批量备份时实现oss的生命周期控制。

**Comment by shellus** [comment]
你说的是本地文件的修改时间被改变了吗？

**Comment by lesgle** [comment]
不是，我说的不是本地文件的修改时间被改变。

而是指当文件上传到oss后，oss上面该文件的修改时间是文件上传这一刻的时间
但是这个时间可能与改文件在本地的修改的时间不一致
这样将会导致在做版本生命周期控制的时候无法确定该文件的过期时间。

**Comment by shellus** [comment]
oss控制面板上显示的“修改时间”那一列，并不是指的文件修改时间，而是oss中一个object最后操作时间。这个是一个只读属性，没有提供设置它的方式，所以你这个需求是无法实现的。

**Comment by lesgle** [comment]
明白了，非常感谢您的回复，谢谢～～

**Comment by detectRecog** [comment]
cp的时候如何能获取所有文件的上传时间戳？
不然数据拉下来都是拉下来的时间，有时候上传时间也是很重要的一个数据，希望你们能够增加这个功能，至少允许用json导出文件夹下所有文件的上传时间
@shellus
