### ISSUE TITLE
只能查看第一个空间的文件，其他空间都是403返回

### ISSUE THREAD

**Issue by 1265578519** [aliyun/ossutil#59]
Error: oss: service returned error: StatusCode=403, ErrorCode=AccessDenied, ErrorMessage=The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint., RequestId=5B8E81775CC26B5BBA097D54, Bucket=test!

**Comment by shellus** [comment]
请检查你的配置文件~/.ossutilconfig 中的endpoint 设置。不同的空间地区不同的话，是需要切换不同的endpoint地址的。
例如你一个杭州的控件，使用的endpoint为北京的地址，那么北京的服务器只会给你返回403了。

**Comment by 1265578519** [comment]
谢谢，之前在百度搜索资料发现问题了，，，介绍文档没注明清楚
