### ISSUE TITLE
./ossutil ls oss:// 报错

### ISSUE THREAD

**Issue by haochencheng** [aliyun/ossutil#63]
./ossutil ls oss://
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6463fb]

goroutine 1 [running]:
github.com/aliyun/aliyun-oss-go-sdk/oss.Conn.doRequest(0xc4201760f0, 0xc4200118c0, 0xc4200118f0, 0x7b59ba, 0x3, 0x0, 0xc420016e4e, 0x1, 0x0, 0x0, ...)
        /home/zubo.yzb/go/src/github.com/aliyun/aliyun-oss-go-sdk/oss/conn.go:192 +0x17b
github.com/aliyun/aliyun-oss-go-sdk/oss.Conn.Do(0xc4201760f0, 0xc4200118c0, 0xc4200118f0, 0x7b59ba, 0x3, 0x0, 0x0, 0x0, 0x0, 0xc4200119b0, ...)
        /home/zubo.yzb/go/src/github.com/aliyun/aliyun-oss-go-sdk/oss/conn.go:59 +0x276
github.com/aliyun/aliyun-oss-go-sdk/oss.Client.do(0xc4201760f0, 0xc4200d2fa0, 0x7b59ba, 0x3, 0x0, 0x0, 0xc4200119b0, 0x0, 0x0, 0x0, ...)
        /home/zubo.yzb/go/src/github.com/aliyun/aliyun-oss-go-sdk/oss/client.go:800 +0xea
github.com/aliyun/aliyun-oss-go-sdk/oss.Client.ListBuckets(0xc4201760f0, 0xc4200d2fa0, 0xc42004f8a0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/zubo.yzb/go/src/github.com/aliyun/aliyun-oss-go-sdk/oss/client.go:143 +0x12c
github.com/aliyun/ossutil/lib.(*ListCommand).ossListBucketsRetry(0x9b62e0, 0xc420041cb0, 0xc42004f8a0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/zubo.yzb/go/src/github.com/aliyun/ossutil/lib/ls.go:461 +0x11f
github.com/aliyun/ossutil/lib.(*ListCommand).listBuckets(0x9b62e0, 0x0, 0x0, 0x0, 0x7ffd1db8d6fc)
        /home/zubo.yzb/go/src/github.com/aliyun/ossutil/lib/ls.go:411 +0x67d
github.com/aliyun/ossutil/lib.(*ListCommand).RunCommand(0x9b62e0, 0x79cde0, 0x9b62e0)
        /home/zubo.yzb/go/src/github.com/aliyun/ossutil/lib/ls.go:380 +0x156
github.com/aliyun/ossutil/lib.(*CommandManager).RunCommand(0xc42004fe18, 0x7ffd1db8d6f9, 0x2, 0xc42005a590, 0x1, 0x3, 0xc420011380, 0x29, 0xc4200185d0, 0x23)
        /home/zubo.yzb/go/src/github.com/aliyun/ossutil/lib/command_manager.go:89 +0x12b
github.com/aliyun/ossutil/lib.RunCommand(0xc42005a580, 0x2, 0x4, 0xc420011380, 0x0, 0x0, 0x7d3da8)
        /home/zubo.yzb/go/src/github.com/aliyun/ossutil/lib/command_manager.go:63 +0x106
github.com/aliyun/ossutil/lib.ParseAndRunCommand(0xc420014ba0, 0x14)
        /home/zubo.yzb/go/src/github.com/aliyun/ossutil/lib/command_manager.go:27 +0x101
main.main()
        /home/zubo.yzb/go/src/github.com/aliyun/ossutil/ossutil.go:12 +0x26

**Comment by hangzws** [comment]
应该是config参数没有配对吧？请确定一下配置是否正确

**Comment by haochencheng** [comment]
![image](https://user-images.githubusercontent.com/20943919/46863372-d5d15380-ce49-11e8-8b80-7ffed4c5c060.png)
这样配置 对吗

**Comment by haochencheng** [comment]
用 osscmd 了。。。
