### ISSUE TITLE
Error: mkdir .ossutil_checkpoint: permission denied!

### ISSUE THREAD

**Issue by kybom** [aliyun/ossutil#65]
执行下面这操作时提示错误：
```
ali@ljp:/var/backups$ ossutil64 cp /var/backups/alihome.tgz oss://alicode/`date +%Y%m%d`/ -f
Error: mkdir .ossutil_checkpoint: permission denied!
```
上传文件要使用到mkdir?
在ali用户的home目录下执行这个命令是正常的。

**Comment by tigerich** [comment]
hit the same issue for my jenkins job. but when I manually execute it there's no such an issue.

**Comment by hxyshare** [comment]
我遇到的情况是，如果你后台已经有正在执行oss命令，再次执行oss命令就有这个报错，可以使用手动指定checkpoint的命令，或者换一个shell tab页。
