### ISSUE TITLE
提点小需求

### ISSUE THREAD

**Issue by yufengshizhe** [aliyun/ossutil#67]
能不能增加一个传输的时候排除某个文件或者文件夹选项
或者传输文件的时候支持通配符或者正则

**Comment by wangtaowei** [comment]
cp命令有include和exclude选项，请用help cp命令查看用法

**Comment by hunkjun** [comment]
貌似不支持 排除目录  比如： ossutilmac64 --part-size=5242880 --exclude "./.git"

Error: --include or --exclude does not support format containing dir info
