### ISSUE TITLE
Unable to include files in ls

### ISSUE THREAD

**Issue by wojciehm** [aliyun/ossutil#73]
Doesn't matter how the ossutil command with ls switch is used it doesn't work.

> ./ossutilmac64 ls oss://macos-backup --include=*.jpg
> Error: invalid usage of "ls" command, reason: the command does not support option: "include", please try "help ls" for more information!
> 
> ./ossutilmac64 ls oss://macos-backup --include= *.jpg
> Error: invalid usage of "ls" command, reason: the command needs at most 1 argument, please try "help ls" for more information!
> 
> ./ossutilmac64 ls oss://macos-backup --include = *.jpg
> Error: invalid usage of "ls" command, reason: the command needs at most 1 argument, please try "help ls" for more information!
> 
> ./ossutilmac64 ls oss://macos-backup --include =*.jpg
> Error: invalid usage of "ls" command, reason: the command does not support option: "include", please try "help ls" for more information!
> 
> ./ossutilmac64 ls oss://macos-backup --include="*.jpg"
> Error: invalid usage of "ls" command, reason: the command does not support option: "include", please try "help ls" for more information!
> 
> ./ossutilmac64 ls oss://macos-backup --include= "*.jpg"
> Error: invalid usage of "ls" command, reason: the command needs at most 1 argument, please try "help ls" for more information!
> 
> /ossutilmac64 ls oss://macos-backup --include = "*.jpg"
> Error: invalid usage of "ls" command, reason: the command needs at most 1 argument, please try "help ls" for more information!

**Comment by huiguangjun** [comment]
已支持。
