### ISSUE TITLE
Linux binary is limited in some version

### ISSUE THREAD

**Issue by mumutu66** [aliyun/ossutil#77]
in alpine 
bash-4.4# ./ossutil64 
bash: ./ossutil64: No such file or directory

I think this should be supported  cuz [MC](https://dl.minio.io/client/mc/release/linux-amd64/mc) does

**Comment by wangtaowei** [comment]
This problem may be caused by not adding the ossutil64 binary path to the PATH environment variable

**Comment by iwhen** [comment]
I met the same problem within docker image(python:3.6-alpine)

```
/opt/project # uname -a
Linux 7a96ac74e60f 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 Linux
/opt/project # ls -lash bin/
total 18964
     0 -rw-r--r--    1 root     root           0 Mar 17 16:46 ?uE@p?@8
     0 drwxr-xr-x    5 root     root         160 Mar 17 16:46 .
     0 drwxr-xr-x    3 root     root          96 Mar 17 16:22 ..
  9572 -rwxr-xr-x    1 root     root        9.1M Mar 17 16:33 ossutil64
/opt/project # export PATH="$PATH:/opt/project/bin"
/opt/project # echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/project/bin
/opt/project # ossutil64
/bin/sh: ossutil64: not found
```

**Comment by wangtaowei** [comment]
1、If you download ossutil64 in docker, there should be no problem
2、If you are using path mapping, you can check the configuration of docker.

**Comment by picarsite** [comment]
There is an easy fix for that.

Run the following command:
> file ossutil64

This gives you the following output:

> ossutil64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=dTcdpS2DM_tbVnspD9EL/cgB4DjKeN2IHghjqLNB2/enJepyG_S9QsL2E5pY6s/nYXqFA3QxMm0MBfGSVV9, not stripped

It shows you that the interpreter "/lib64/ld-linux-x86-64.so.2" is needed to be able to execute this binary.  
That means that you just have to install the "libc6-compat" package of Alpine:

> apk update
> apk add libc6-compat

Have fun!

**Comment by mumutu66** [comment]
@picarsite  ..wow glad to see the easy solution  thanks a lot ! 
@wangtaowei it's a non-trivial problem for the beginner  so I think it should be mentioned  somewhere within the doc
