### ISSUE TITLE
Please add stdout support for copy to local file system

### ISSUE THREAD

**Issue by ghost** [aliyun/ossutil#82]
For performance testing it would be helpful if copy supported writing to stdout or at least /dev/null. For example, `aws s3` supports writing to stdout using `-` as the local path.

**Comment by huiguangjun** [comment]
ossutil 2.0 预览版(https://help.aliyun.com/zh/oss/developer-reference/command-line-tool-ossutil-version-2) 已发布，

该版已支持 - 参数，即从 标准输入读取 或者 输出到标准输入上 

如何从 ossutil 1.0 迁移到 ossutil 2.0，请参见 [迁移指南](https://help.aliyun.com/zh/oss/developer-reference/migration-guide/)
