### ISSUE TITLE
ubuntu软件包

### ISSUE THREAD

**Issue by zhaofeng-shu33** [aliyun/ossutil#83]
我想把ossutil打包，放到ppa上，这样在添加了ppa源的ubuntu系统中安装、更新、uninstall etc 都比较方便，不知道 aliyun有没有开 自己的ppa，或者可以让用户自己弄。

**Comment by wangtaowei** [comment]
现在是没有ppa相关的支持的，不过您可以用update命令，就可以自动将工具升级到最新版本了
比如 ossutil64 update
