### ISSUE TITLE
上传速度显示错误

### ISSUE THREAD

**Issue by kybom** [aliyun/ossutil#94]
ossutile version:1.6.3

cp 上传进度错误
![QQ截图20190624174633](https://user-images.githubusercontent.com/24692485/60009552-aa755880-96a8-11e9-94a8-5263e2fb27c2.png)
size,progree,speed都显示错误，speed还会出现负值。

**Comment by wangtaowei** [comment]
Thank you，it‘s a bug，
We will solve this problem in the latest version in mid-July
