### ISSUE TITLE
Remove large number of files

### ISSUE THREAD

**Issue by jhagege** [aliyun/ossutil#97]
When trying to ossutil rm a large number of files, I get the following error:
Total 1002 objects. Removed 100 objects. when error happens.
Error: oss: service returned error: StatusCode=400, ErrorCode=MalformedXML, ErrorMessage="The XML you provided was not well-formed or did not validate against our published schema.", RequestId=5D3F0D47C1E6C9CDCBBD3B8F

What is the suggested way to delete a large number of objects ?
Thanks

**Comment by wangtaowei** [comment]
the error message maybe wrong
the real reason is perhaps that you have not rigth to delete objects
